# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: heretic-monkeydotcom - Build and deploy app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod

      - name: Install
        run: npm install && cd server && npm install && cd ..

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Build App
        run: ng build -c production

      - name: Transpile Server
        run: tsc -p server/tsconfig.json

      - name: Zip artifact for deployment
        run: tar -zcf dist.zip dist && rm -r dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 'dist.zip'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Unzip artifact for deployment
        run: tar -xf dist.zip dist

      - name: Move server code down to wwwroot
        run: mv dist/server/* ./

      - name: Move client code down to wwwroot
        run: mv dist/browser/* ./

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72012F24D9714053A82BAC464D45169F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C9B79B2D48F44A548B631B603111D8CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_437D1E112C274A0E9235F40D83E1E943 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'heretic-monkeydotcom'
          slot-name: 'Production'
          package: .

      - name: Automatically run node index.js
        run: /usr/bin/az webapp config set --resource-group heretic-monkey.com --name heretic-monkeydotcom --startup-file "pm2 start index.js --no-daemon"
